name: Linux OS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run:  sudo apt-get install make 
      
    - name: make all
      run:  make all -C M1_LSB_IMAGE_Steganography_systemsecurity/3_Implementation/
